import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Make sure the CSS with the background is loaded here
import Navbar from "@/components/header";
import Footer from "@/components/footer"; // Uncomment Footer if you plan to include it

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${inter.className} page-background`}>
        {/* Background overlay div */}
        <div className="background-overlay"></div>


        {/* <Navbar /> */}
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}

